### ISSUE TITLE
As a USER, I want to login into the application by providing valid credentials

### ISSUE THREAD

**Issue by saikiranreddygangidi** [saikiranreddygangidi/connectcompany#4]
- [x]  User should be authenticated on providing valid credentials.
- [x]  Or else in another case User should be displayed with a proper message in case of invalid credentials.
- [x]  User should be able to register for the events successfully.

**Comment by jarugulavenkat7** [comment]
### As a user I am able to successfully login into the application, after providing valid credentials.
### Below are the screenshots showing the login activity
![Screenshot (65)](https://user-images.githubusercontent.com/47450387/139613267-de97dd66-d16b-4a5c-8815-095a7483f1ab.png)
![Screenshot (67)](https://user-images.githubusercontent.com/47450387/139613337-23226541-fb46-4ed4-8c84-2597de7455c7.png)
![Screenshot (68)](https://user-images.githubusercontent.com/47450387/139613348-a4e6647f-a45c-4e42-8299-a9059680945e.png)

**Comment by swetha34** [comment]
### Testing Results:
We have done  testing by providing both valid and invalid credentials in the login page.
![Screenshot (120)](https://user-images.githubusercontent.com/77765985/139715676-5aa125cf-939a-4834-9f86-35aed85c2f2a.png)
