### ISSUE TITLE
   As as User ,Admin , Commitee Member need to have the different welcome page and operations which should be categories based upon the role

### ISSUE THREAD

**Issue by saikiranreddygangidi** [saikiranreddygangidi/connectcompany#5]
- [x]  User should be authenticated on providing valid credentials and also check all the fields are given or not
- [x]  Or else in another case User should be displayed with a proper message in case of invalid credentials.
- [x]  User should be able to register for the events successfully.

**Comment by vivekd31** [comment]
async login({ request, response, auth }) {
    const userinfo = request.only(["username", "code"]);
    const rules = {
      username: "required",
      code: "required",
    };

    const validation = await validate(userinfo, rules);

    if (validation.fails()) {
      return response.badRequest({
        error: {
          status: 401,
          message: "bad request, missing some required for connectcompony",
          fields: validation.messages(),
        },
      });
    }
    if (!userinfo.username || !userinfo.code) {
      console.error(
        "AuthController-login, missing required attributes: email/password"
      );
      return response.status(400).json({
        error: {
          status: 400,
          message: "bad request, username and code are required",
        },
      });
    }

    const Securitykey = "82f2ceed4c503896c8a291e560bd4325";
    const initVector = "sinasinasisinaaa";
    const algorithm = "aes-256-cbc";

    const decipher = crypto.createDecipheriv(
      algorithm,
      Securitykey,
      initVector
    );

    let decryptedData = decipher.update(userinfo.code, "base64", "utf-8");

    decryptedData += decipher.final("utf8");

    userinfo.code = decryptedData;

    const user = await User.query()
      .where("username", userinfo.username)
      .where("code", userinfo.code)
      .fetch();

    if (user.rows.length > 0) {
    //  let jwtToken = await auth.generate(user);

      return response.status(200).json({
        message: "authenticated",
        data: user,
       // token: jwtToken.token,
      });
    } else {
      return response.status(500).json({
        message: "unauthenticated user",
      });
      
      The above code works when the user gives invalid credentials then he will receive a proper error message.

**Comment by Nikhilreddy012** [comment]
I changed the code to check if all of the fields are filled in using Validator.
It must be set up.

  const rules = {
      email: 'required|email|unique:users,email',
      code: 'required',
    };

    const validation = await validate(userInfo, rules);


  if (validation.fails()) {
    return response.badRequest({
      error: {
        status: 401,
        message:
          "bad request, missing some required for internship properties",
        fields: validation.messages(),
      },
    });
  }
