### ISSUE TITLE
As a USER, I should be shown with valid error message if I provide invalid credentials and use secure approach to reduce man in middle attack

### ISSUE THREAD

**Issue by vivekd31** [saikiranreddygangidi/connectcompany#6]
- [x] Given, Or else in another case User should be displayed with a proper message in case of invalid credentials

**Comment by saikiranreddygangidi** [comment]
I have updated the login with crypto encryption and decryption where the password will be encrypted in the frontend and decrypted in the backend for validation . This approach will the man in the middle attack.

To install crypto algorithm L

I have used npm install crypto-js for both frontend and backend

**Comment by vivekd31** [comment]
There is an issue with a login that is it is not showing the error message when we all the people doesn't  entering all the field so I have used validation package .

Below is the code that i changed for vaildation all the fileds in register and login

for login:
const validation = await validate(userinfo, rules);

    if (validation.fails()) {
      return response.badRequest({
        error: {
          status: 401,
          message: "bad request, missing some required for connectcompony",
          fields: validation.messages(),
        },
      });
    }

for register :

const rules = {
        email: "required",
        code: "required",
        username: "required",
      };

      const validation = await validate(request.post(), rules);

      if (validation.fails()) {
        return response.badRequest({
          error: {
            status: 401,
            message:
              "bad request, missing some required for register properties",
            fields: validation.messages(),
          },
        });
      }
